apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base
images:
  - name: ai-conductor-image-url
    newName:
    newTag:
replicas:
  - name: frontend-server
    count: 2
