apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-conductor-web
  namespace: ai-conductor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-conductor
      app.kubernetes.io/name: ai-conductor-web
  template:
    metadata:
      labels:
        app: ai-conductor
        app.kubernetes.io/name: ai-conductor-web
    spec:
      containers:
        - name: web-backend
          image: ai-conductor-image-url
          imagePullPolicy: Always
          ports:
            - name: aic-web-http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: 80
          readinessProbe:
            httpGet:
              path: /api/v1/healthz
              port: 80
          env:
            - name: AIC_IS_PRODUCT_ENV
              value: "1"
            - name: AIC_MYSQL_DB
              value: "ai_conductor"
            - name: LDAP_ENABLED
              value: "false"
            - name: AIC_MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: host
            - name: AIC_MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: port
            - name: AIC_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: AIC_MYSQL_PW
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: redis-config
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: redis-config
      nodeSelector:
        aic-role: controller
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ai-conductor-web
      serviceAccountName: ai-conductor-sa
