apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-secrets-sync
  namespace: ai-conductor
spec:
  selector:
    matchLabels:
      app: aws-secrets-sync
  template:
    metadata:
      labels:
        app: aws-secrets-sync
    spec:
      containers:
        - name: secrets
          image: public.ecr.aws/xray/aws-xray-daemon:latest
          volumeMounts:
              - name: rds-secret
                mountPath: "/mnt/rds-store"
                readOnly: true
      serviceAccountName: ai-conductor-sa
      volumes:
        - name: rds-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "rds-secret"
      nodeSelector:
        aic-role: controller
