infra_name: mk
deploy_env: dev-joseph
serviceaccountname: ai-conductor-joseph-sa # Replace with actual resource's name
redis:
  host: master.redis-an2-meerkat-dev-private.4yv4cy.apn2.cache.amazonaws.com
  port: "6379"
rds_secretmanager: "/parameter/ap-northeast-2/meerkat/dev/rds"
webserver:
  images:
    tag: "2.1.0"
  replicas:
    name: ai-conductor-web
    count: 1
  nodePort: 32030 # Replace with actual port number
  nodeSelector:
    value: mellerikat-sagemaker # Replace with actual resource's name
  config:
    general:
      ecr_base_path: "339713051385.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-repo-an2-meerkat-dev/"
      mysql_db: "ai_conductor_joseph" # Replace with actual resource's name
    ldap:
      enabled: "false" # "true", "false"
      ldap_crt_file: ./params/crt_for_ldap.crt # put ldap crt file here if you want to enable ldap service.
      host_name: "ldaps://lgesaapds01.lge.net"
      host_port: "636"
      base_dn: "OU=LGE Users,dc=LGE,dc=NET"
      search_dn: "dc=lge,dc=net"
      bind_id: "{login_id}@lge.net"
      query: "(cn={login_id})"
      ca_cert: "/etc/aic/lge_root_ca.crt"
    monitor:
      type: "none" # "none", "grafana", "aic"
      grafana:
        org_id: "1"
        dashboard_prefix: "https://aicond-mon-joseph.mellerikat-dev.com/d/" # Replace with actual resource's name
    mlops:
      engine: "sagemaker" # "sagemaker", "kubeflow" 
      # Fill either field below
      kubeflow:
        cluster_name: "eks-an2-meerkat-dev-eks-master"
        nodegroup_label: "mellerikat-sagemaker"
        dashboard_svc: "disable" # "enable", "disable"
        nodePort: 32032 # Replace with actual port number
      sagemaker:
        role_arn: "arn:aws:iam::339713051385:role/service-role/SageMaker-test" # Replace with actual resource's name
        train_tags: "Cost Type:COMPUTING,Company:LGE"
frontend:
  deploy: false
  nodePort: 32031
