apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base
patches:
  - path: ./patches/do-not-create-namespace.yaml
configMapGenerator:
  - name: redis-config
    namespace: ai-conductor
    options:
      disableNameSuffixHash: true
    envs:
      - ./params/redis.env
images:
  - name: ai-conductor-image-url
    newName:
    newTag:
replicas:
  - name: ai-conductor-web
    count: 4
