apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-conductor-web
  name: ai-conductor-web
  namespace: ai-conductor
spec:
  ports:
  - name: http
    nodePort: 30030
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ai-conductor
    app.kubernetes.io/name: ai-conductor-web
  type: NodePort
