apiVersion: v1
kind: Service
metadata:
  name: istio-nodeport-gateway
  namespace: istio-system
  labels:
    app: istio-nodeport-gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30040
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
